name: proxmox

on: 
  workflow_dispatch:
 
jobs:
  proxmox:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Tailscale, QEMU.
        run: |
          sudo apt update -y
          sudo apt install git wget qemu-kvm -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Setting up "IMG" And Starting Proxmox..
        run: |
          bash qemu-img create -f qcow2 /mnt/a.img 127G
          wget -O proxmox.iso https://enterprise.proxmox.com/iso/proxmox-ve_8.2-1.iso
          websockify --web /usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &
          qemu-system-x86_64 -machine q35 -m 12G -cpu host -smp 3 -hda /mnt/a.img -cdrom proxmox.iso -vga virtio -vnc :0 -accel kvm
