name: android

on: 
  workflow_dispatch:
 
jobs:
  android:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Tailscale, QEMU.
        run: |
          sudo apt update -y
          sudo apt install git wget aria2 qemu-kvm websockify novnc tigervnc-standalone-server -y
          curl -fsSL https://tailscale.com/install.sh | sh
          sudo tailscale up
      - name: Setting up "IMG" And Starting Proxmox..
        run: |
          sudo qemu-img create -f qcow2 /mnt/a.img 127G
          sudo wget https://unlimited.dl.sourceforge.net/project/android-x86/Release%209.0/android-x86_64-9.0-r2.iso
          sudo websockify --web /usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &
          sudo qemu-system-x86_64 -machine q35 -m 12G -cpu host -smp 3 -hda /mnt/a.img -cdrom android-x86_64-9.0-r2.iso -vga virtio -vnc :0 -accel kvm
