name: Android 

on: 
  workflow_dispatch:
 
jobs:
  android:
    runs-on: ubuntu-22.04
    steps:

      - name: Getting Updates and Installing Playit.GG, QEMU.
        run: |
          sudo apt update -y
          sudo apt install aria2 qemu-kvm websockify novnc tigervnc-standalone-server -y
          sudo wget https://github.com/Efebey2903/android-playitgg/raw/main/loop.sh
          sudo chmod +x loop.sh
          sudo wget -O playit https://github.com/playit-cloud/playit-agent/releases/download/v0.15.23/playit-linux-amd64
          sudo chmod +x playit
          sudo nohup ./playit &> a.log &
      - name: Making Android and Setting Everything Up.
        run: |
          sudo aria2c -s16 -x16 -o android.iso https://pixeldrain.com/api/file/BTwiJpGj?download
          sudo qemu-img create -f raw /mnt/a.img 70G
          websockify --web /usr/share/novnc/ --wrap-mode=ignore 6080 localhost:5900 &
          sleep 2
          sudo nohup qemu-system-x86_64 -machine q35 -m 14G -cpu host -smp 3 -hda /mnt/a.img -cdrom android.iso -vga virgl-gpu -vnc :0 -netdev user,id=net0,hostfwd=tcp::8006-:8006 -device virtio-net-pci,netdev=net0 -accel kvm -bios /usr/share/ovmf/OVMF.fd &> /dev/null &
          bash loop.sh
